#!/bin/sh -e
# postrm script for mysql-connector-python

PY2VERS=`pyversions -sv | sed -e "s/\s*2\.5\s*//g"`

for PYVER in $PY2VERS; do
    PYSHARED="/usr/share/pyshared"
    PYDIST=`python$PYVER -c "from distutils.sysconfig import get_python_lib; print (get_python_lib())"`

    # Try to remove the MySQL top package mysql/
    if [ -d $PYSHARED/mysql ];
    then
        SUBPKGS=`ls --ignore=*.pyc --ignore=*.pyo -m $PYSHARED/mysql`
        if [ "$SUBPKGS" = "__init__.py" ];
        then
            rm $PYSHARED/mysql/__init__.py*
            rmdir $PYSHARED/mysql/
        fi
    fi

    if [ -d $PYDIST/mysql ];
    then
        SUBPKGS=`ls --ignore=*.pyc --ignore=*.pyo -m $PYDIST/mysql`
        if [ "$SUBPKGS" = "__init__.py" ];
        then
            rm $PYDIST/mysql/__init__.py*
            # Remove folder and symlink
            rmdir $PYDIST/mysql/
        fi
    fi
done

if [ "`which py3versions 2>/dev/null`" != "" ]; then
    PY3VERS=`py3versions -iv`
    for PYVER in $(py3versions -iv); do 
        PYDIST=`python$PYVER -c "from distutils.sysconfig import get_python_lib; print (get_python_lib())"`
        if [ -d $PYDIST/mysql ];
        then
            SUBPKGS=`ls --ignore=*.pyc --ignore=*.pyo -m $PYDIST/mysql`
            if [ "$SUBPKGS" = "__init__.py" ];
            then
                rm $PYDIST/mysql/__init__.py*
                rmdir $PYDIST/mysql/
            fi
        fi
    done
fi

#DEBHELPER#

exit 0
